# Generated by Django 3.1.7 on 2021-04-06 10:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0002_auto_20210406_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('title', models.CharField(choices=[('INTERNATIONAL', 'international'), ('EDUCATION', 'education'), ('SPORT', 'sport'), ('LOCAL', 'local'), ('ENTERTAINMENT', 'entertainment')], default='draft', max_length=15)),
                ('description', models.TextField()),
                ('description2', models.TextField(blank=True)),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('video', models.FileField(null=True, upload_to='videos/%Y/%m/%d/', verbose_name='')),
                ('video1', models.FileField(null=True, upload_to='videos/%Y/%m/%d/', verbose_name='')),
                ('is_published', models.BooleanField(default=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.team')),
            ],
        ),
    ]
