# Generated by Django 3.1.7 on 2021-04-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.FileField(null=True, upload_to='videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='video1',
            field=models.FileField(null=True, upload_to='videos/%Y/%m/%d/'),
        ),
    ]
