# Generated by Django 3.1.7 on 2021-04-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210406_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='video1',
            field=models.TextField(blank=True),
        ),
    ]
