# Generated by Django 3.1.7 on 2021-04-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210416_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(choices=[('International', 'international'), ('Education', 'education'), ('Sport', 'sport'), ('Local', 'local'), ('Entertainment', 'entertainment')], default='draft', max_length=15),
        ),
    ]
